# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a828f30b-4ec6-4f84-b30a-c318a0e8ca36"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :ios do
  gym(
    export_method: "development"
  )
  # upload to Beta by Crashlytics
  crashlytics(
#    ipa_path: "../Runner.ipa"
  )
end
